[package]
name = "Q1"
version = "0.1.0"
authors = ["hamza mahmood <hamzamahmood1124@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
